/*
 * FINBOURNE Identity Service API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.identity.api;

import com.finbourne.identity.ApiCallback;
import com.finbourne.identity.ApiClient;
import com.finbourne.identity.ApiException;
import com.finbourne.identity.ApiResponse;
import com.finbourne.identity.Configuration;
import com.finbourne.identity.Pair;
import com.finbourne.identity.ProgressRequestBody;
import com.finbourne.identity.ProgressResponseBody;
import com.finbourne.identity.extensions.ConfigurationOptions;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.finbourne.identity.model.LusidProblemDetails;
import com.finbourne.identity.model.LusidValidationProblemDetails;
import com.finbourne.identity.model.McpToolResponse;
import com.finbourne.identity.model.UpsertMcpToolRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class McpToolsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public McpToolsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public McpToolsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call createMcpToolCall(String scope, String code, UpsertMcpToolRequest upsertMcpToolRequest, final ApiCallback _callback) throws ApiException {
        return createMcpToolCall(scope, code, upsertMcpToolRequest,  _callback, new ConfigurationOptions());
    }

    private okhttp3.Call createMcpToolCall(String scope, String code, UpsertMcpToolRequest upsertMcpToolRequest, final ApiCallback _callback, ConfigurationOptions opts) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = upsertMcpToolRequest;

        // create path and map variables
        String localVarPath = "/api/mcptools/{scope}/{code}"
            .replace("{" + "scope" + "}", localVarApiClient.escapeString(scope.toString()))
            .replace("{" + "code" + "}", localVarApiClient.escapeString(code.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json-patch+json",
            "application/json",
            "text/json",
            "application/*+json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "oauth2" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback, opts);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createMcpToolValidateBeforeCall(String scope, String code, UpsertMcpToolRequest upsertMcpToolRequest, final ApiCallback _callback, ConfigurationOptions opts) throws ApiException {
        // verify the required parameter 'scope' is set
        if (scope == null) {
            throw new ApiException("Missing the required parameter 'scope' when calling createMcpTool(Async)");
        }

        // verify the required parameter 'code' is set
        if (code == null) {
            throw new ApiException("Missing the required parameter 'code' when calling createMcpTool(Async)");
        }

        // verify the required parameter 'upsertMcpToolRequest' is set
        if (upsertMcpToolRequest == null) {
            throw new ApiException("Missing the required parameter 'upsertMcpToolRequest' when calling createMcpTool(Async)");
        }

        return createMcpToolCall(scope, code, upsertMcpToolRequest, _callback, opts);

    }


    private ApiResponse<McpToolResponse> createMcpToolWithHttpInfo(String scope, String code, UpsertMcpToolRequest upsertMcpToolRequest) throws ApiException {
        okhttp3.Call localVarCall = createMcpToolValidateBeforeCall(scope, code, upsertMcpToolRequest, null, new ConfigurationOptions());
        Type localVarReturnType = new TypeToken<McpToolResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private ApiResponse<McpToolResponse> createMcpToolWithHttpInfo(String scope, String code, UpsertMcpToolRequest upsertMcpToolRequest, ConfigurationOptions opts) throws ApiException {
        okhttp3.Call localVarCall = createMcpToolValidateBeforeCall(scope, code, upsertMcpToolRequest, null, opts);
        Type localVarReturnType = new TypeToken<McpToolResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call createMcpToolAsync(String scope, String code, UpsertMcpToolRequest upsertMcpToolRequest, final ApiCallback<McpToolResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = createMcpToolValidateBeforeCall(scope, code, upsertMcpToolRequest, _callback, new ConfigurationOptions());
        Type localVarReturnType = new TypeToken<McpToolResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    private okhttp3.Call createMcpToolAsync(String scope, String code, UpsertMcpToolRequest upsertMcpToolRequest, final ApiCallback<McpToolResponse> _callback, ConfigurationOptions opts) throws ApiException {

        okhttp3.Call localVarCall = createMcpToolValidateBeforeCall(scope, code, upsertMcpToolRequest, _callback, opts);
        Type localVarReturnType = new TypeToken<McpToolResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class APIcreateMcpToolRequest {
        private final String scope;
        private final String code;
        private final UpsertMcpToolRequest upsertMcpToolRequest;

        private APIcreateMcpToolRequest(String scope, String code, UpsertMcpToolRequest upsertMcpToolRequest) {
            this.scope = scope;
            this.code = code;
            this.upsertMcpToolRequest = upsertMcpToolRequest;
        }

        /**
         * Build call for createMcpTool
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 201 </td><td> Create MCP Tool </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> The details of the input related failure </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Error response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return createMcpToolCall(scope, code, upsertMcpToolRequest, _callback);
        }

        /**
         * Execute createMcpTool request
         * @return McpToolResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 201 </td><td> Create MCP Tool </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> The details of the input related failure </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Error response </td><td>  -  </td></tr>
         </table>
         */
        public McpToolResponse execute() throws ApiException {
            ApiResponse<McpToolResponse> localVarResp = createMcpToolWithHttpInfo(scope, code, upsertMcpToolRequest);
            return localVarResp.getData();
        }

        /**
         * Execute createMcpTool request. Use any specified configuration options to override any other configuration for this request only.
         * @return McpToolResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 201 </td><td> Create MCP Tool </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> The details of the input related failure </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Error response </td><td>  -  </td></tr>
         </table>
         */
        public McpToolResponse execute(ConfigurationOptions opts) throws ApiException {
            ApiResponse<McpToolResponse> localVarResp = createMcpToolWithHttpInfo(scope, code, upsertMcpToolRequest, opts);
            return localVarResp.getData();
        }

        /**
         * Execute createMcpTool request with HTTP info returned
         * @return ApiResponse&lt;McpToolResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 201 </td><td> Create MCP Tool </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> The details of the input related failure </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Error response </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<McpToolResponse> executeWithHttpInfo() throws ApiException {
            return createMcpToolWithHttpInfo(scope, code, upsertMcpToolRequest);
        }

        /**
         * Execute createMcpTool request with HTTP info returned. Use any specified configuration options to override any other configuration for this request only.
         * @return ApiResponse&lt;McpToolResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 201 </td><td> Create MCP Tool </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> The details of the input related failure </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Error response </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<McpToolResponse> executeWithHttpInfo(ConfigurationOptions opts) throws ApiException {
            return createMcpToolWithHttpInfo(scope, code, upsertMcpToolRequest, opts);
        }

        /**
         * Execute createMcpTool request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 201 </td><td> Create MCP Tool </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> The details of the input related failure </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Error response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<McpToolResponse> _callback) throws ApiException {
            return createMcpToolAsync(scope, code, upsertMcpToolRequest, _callback);
        }

        /**
         * Execute createMcpTool request (asynchronously). Use any specified configuration options to override any other configuration for this request only.
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 201 </td><td> Create MCP Tool </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> The details of the input related failure </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Error response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<McpToolResponse> _callback, ConfigurationOptions opts) throws ApiException {
            return createMcpToolAsync(scope, code, upsertMcpToolRequest, _callback, opts);
        }
    }

    /**
     * [EARLY ACCESS] CreateMcpTool: Create an MCP Tool
     * Creates a new MCP tool definition
     * @param scope The scope of the MCP tool (required)
     * @param code The code of the MCP tool (required)
     * @param upsertMcpToolRequest The MCP tool definition (required)
     * @return APIcreateMcpToolRequest
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Create MCP Tool </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The details of the input related failure </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Error response </td><td>  -  </td></tr>
     </table>
     */
    public APIcreateMcpToolRequest createMcpTool(String scope, String code, UpsertMcpToolRequest upsertMcpToolRequest) {
        return new APIcreateMcpToolRequest(scope, code, upsertMcpToolRequest);
    }
    private okhttp3.Call deleteMcpToolCall(String scope, String code, final ApiCallback _callback) throws ApiException {
        return deleteMcpToolCall(scope, code,  _callback, new ConfigurationOptions());
    }

    private okhttp3.Call deleteMcpToolCall(String scope, String code, final ApiCallback _callback, ConfigurationOptions opts) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/mcptools/{scope}/{code}"
            .replace("{" + "scope" + "}", localVarApiClient.escapeString(scope.toString()))
            .replace("{" + "code" + "}", localVarApiClient.escapeString(code.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "oauth2" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback, opts);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteMcpToolValidateBeforeCall(String scope, String code, final ApiCallback _callback, ConfigurationOptions opts) throws ApiException {
        // verify the required parameter 'scope' is set
        if (scope == null) {
            throw new ApiException("Missing the required parameter 'scope' when calling deleteMcpTool(Async)");
        }

        // verify the required parameter 'code' is set
        if (code == null) {
            throw new ApiException("Missing the required parameter 'code' when calling deleteMcpTool(Async)");
        }

        return deleteMcpToolCall(scope, code, _callback, opts);

    }


    private ApiResponse<Void> deleteMcpToolWithHttpInfo(String scope, String code) throws ApiException {
        okhttp3.Call localVarCall = deleteMcpToolValidateBeforeCall(scope, code, null, new ConfigurationOptions());
        return localVarApiClient.execute(localVarCall);
    }

    private ApiResponse<Void> deleteMcpToolWithHttpInfo(String scope, String code, ConfigurationOptions opts) throws ApiException {
        okhttp3.Call localVarCall = deleteMcpToolValidateBeforeCall(scope, code, null, opts);
        return localVarApiClient.execute(localVarCall);
    }

    private okhttp3.Call deleteMcpToolAsync(String scope, String code, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteMcpToolValidateBeforeCall(scope, code, _callback, new ConfigurationOptions());
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }

    private okhttp3.Call deleteMcpToolAsync(String scope, String code, final ApiCallback<Void> _callback, ConfigurationOptions opts) throws ApiException {

        okhttp3.Call localVarCall = deleteMcpToolValidateBeforeCall(scope, code, _callback, opts);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }

    public class APIdeleteMcpToolRequest {
        private final String scope;
        private final String code;

        private APIdeleteMcpToolRequest(String scope, String code) {
            this.scope = scope;
            this.code = code;
        }

        /**
         * Build call for deleteMcpTool
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 204 </td><td> No Content </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> The details of the input related failure </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Error response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return deleteMcpToolCall(scope, code, _callback);
        }

        /**
         * Execute deleteMcpTool request
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 204 </td><td> No Content </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> The details of the input related failure </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Error response </td><td>  -  </td></tr>
         </table>
         */
        public void execute() throws ApiException {
            deleteMcpToolWithHttpInfo(scope, code);
        }

        /**
         * Execute deleteMcpTool request
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 204 </td><td> No Content </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> The details of the input related failure </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Error response </td><td>  -  </td></tr>
         </table>
         */
        public void execute(ConfigurationOptions opts) throws ApiException {
            deleteMcpToolWithHttpInfo(scope, code, opts);
        }

        /**
         * Execute deleteMcpTool request with HTTP info returned
         * @return ApiResponse&lt;Void&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 204 </td><td> No Content </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> The details of the input related failure </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Error response </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<Void> executeWithHttpInfo() throws ApiException {
            return deleteMcpToolWithHttpInfo(scope, code);
        }

        /**
         * Execute deleteMcpTool request with HTTP info returned. Use any specified configuration options to override any other configuration for this request only.
         * @return ApiResponse&lt;Void&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 204 </td><td> No Content </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> The details of the input related failure </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Error response </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<Void> executeWithHttpInfo(ConfigurationOptions opts) throws ApiException {
            return deleteMcpToolWithHttpInfo(scope, code, opts);
        }

        /**
         * Execute deleteMcpTool request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 204 </td><td> No Content </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> The details of the input related failure </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Error response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<Void> _callback) throws ApiException {
            return deleteMcpToolAsync(scope, code, _callback);
        }

        /**
         * Execute deleteMcpTool request (asynchronously). Use any specified configuration options to override any other configuration for this request only.
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 204 </td><td> No Content </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> The details of the input related failure </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Error response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<Void> _callback, ConfigurationOptions opts) throws ApiException {
            return deleteMcpToolAsync(scope, code, _callback, opts);
        }
    }

    /**
     * [EARLY ACCESS] DeleteMcpTool: Delete an MCP Tool
     * Deletes an MCP tool (soft delete - closes the current version)
     * @param scope The scope of the MCP tool (required)
     * @param code The code of the MCP tool (required)
     * @return APIdeleteMcpToolRequest
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> No Content </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The details of the input related failure </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Error response </td><td>  -  </td></tr>
     </table>
     */
    public APIdeleteMcpToolRequest deleteMcpTool(String scope, String code) {
        return new APIdeleteMcpToolRequest(scope, code);
    }
    private okhttp3.Call getMcpToolCall(String scope, String code, Integer version, final ApiCallback _callback) throws ApiException {
        return getMcpToolCall(scope, code, version,  _callback, new ConfigurationOptions());
    }

    private okhttp3.Call getMcpToolCall(String scope, String code, Integer version, final ApiCallback _callback, ConfigurationOptions opts) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/mcptools/{scope}/{code}"
            .replace("{" + "scope" + "}", localVarApiClient.escapeString(scope.toString()))
            .replace("{" + "code" + "}", localVarApiClient.escapeString(code.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (version != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("version", version));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "oauth2" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback, opts);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getMcpToolValidateBeforeCall(String scope, String code, Integer version, final ApiCallback _callback, ConfigurationOptions opts) throws ApiException {
        // verify the required parameter 'scope' is set
        if (scope == null) {
            throw new ApiException("Missing the required parameter 'scope' when calling getMcpTool(Async)");
        }

        // verify the required parameter 'code' is set
        if (code == null) {
            throw new ApiException("Missing the required parameter 'code' when calling getMcpTool(Async)");
        }

        return getMcpToolCall(scope, code, version, _callback, opts);

    }


    private ApiResponse<McpToolResponse> getMcpToolWithHttpInfo(String scope, String code, Integer version) throws ApiException {
        okhttp3.Call localVarCall = getMcpToolValidateBeforeCall(scope, code, version, null, new ConfigurationOptions());
        Type localVarReturnType = new TypeToken<McpToolResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private ApiResponse<McpToolResponse> getMcpToolWithHttpInfo(String scope, String code, Integer version, ConfigurationOptions opts) throws ApiException {
        okhttp3.Call localVarCall = getMcpToolValidateBeforeCall(scope, code, version, null, opts);
        Type localVarReturnType = new TypeToken<McpToolResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call getMcpToolAsync(String scope, String code, Integer version, final ApiCallback<McpToolResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getMcpToolValidateBeforeCall(scope, code, version, _callback, new ConfigurationOptions());
        Type localVarReturnType = new TypeToken<McpToolResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    private okhttp3.Call getMcpToolAsync(String scope, String code, Integer version, final ApiCallback<McpToolResponse> _callback, ConfigurationOptions opts) throws ApiException {

        okhttp3.Call localVarCall = getMcpToolValidateBeforeCall(scope, code, version, _callback, opts);
        Type localVarReturnType = new TypeToken<McpToolResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class APIgetMcpToolRequest {
        private final String scope;
        private final String code;
        private Integer version;

        private APIgetMcpToolRequest(String scope, String code) {
            this.scope = scope;
            this.code = code;
        }

        /**
         * Set version
         * @param version Optional version number to retrieve. If not specified, returns the current version. (optional)
         * @return APIgetMcpToolRequest
         */
        public APIgetMcpToolRequest version(Integer version) {
            this.version = version;
            return this;
        }

        /**
         * Build call for getMcpTool
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Get MCP Tool </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> The details of the input related failure </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Error response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return getMcpToolCall(scope, code, version, _callback);
        }

        /**
         * Execute getMcpTool request
         * @return McpToolResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Get MCP Tool </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> The details of the input related failure </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Error response </td><td>  -  </td></tr>
         </table>
         */
        public McpToolResponse execute() throws ApiException {
            ApiResponse<McpToolResponse> localVarResp = getMcpToolWithHttpInfo(scope, code, version);
            return localVarResp.getData();
        }

        /**
         * Execute getMcpTool request. Use any specified configuration options to override any other configuration for this request only.
         * @return McpToolResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Get MCP Tool </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> The details of the input related failure </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Error response </td><td>  -  </td></tr>
         </table>
         */
        public McpToolResponse execute(ConfigurationOptions opts) throws ApiException {
            ApiResponse<McpToolResponse> localVarResp = getMcpToolWithHttpInfo(scope, code, version, opts);
            return localVarResp.getData();
        }

        /**
         * Execute getMcpTool request with HTTP info returned
         * @return ApiResponse&lt;McpToolResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Get MCP Tool </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> The details of the input related failure </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Error response </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<McpToolResponse> executeWithHttpInfo() throws ApiException {
            return getMcpToolWithHttpInfo(scope, code, version);
        }

        /**
         * Execute getMcpTool request with HTTP info returned. Use any specified configuration options to override any other configuration for this request only.
         * @return ApiResponse&lt;McpToolResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Get MCP Tool </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> The details of the input related failure </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Error response </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<McpToolResponse> executeWithHttpInfo(ConfigurationOptions opts) throws ApiException {
            return getMcpToolWithHttpInfo(scope, code, version, opts);
        }

        /**
         * Execute getMcpTool request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Get MCP Tool </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> The details of the input related failure </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Error response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<McpToolResponse> _callback) throws ApiException {
            return getMcpToolAsync(scope, code, version, _callback);
        }

        /**
         * Execute getMcpTool request (asynchronously). Use any specified configuration options to override any other configuration for this request only.
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Get MCP Tool </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> The details of the input related failure </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Error response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<McpToolResponse> _callback, ConfigurationOptions opts) throws ApiException {
            return getMcpToolAsync(scope, code, version, _callback, opts);
        }
    }

    /**
     * [EARLY ACCESS] GetMcpTool: Get an MCP Tool
     * Retrieves an MCP tool. If version is specified, retrieves that specific version for audit purposes. Otherwise, retrieves the current version.
     * @param scope The scope of the MCP tool (required)
     * @param code The code of the MCP tool (required)
     * @return APIgetMcpToolRequest
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Get MCP Tool </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The details of the input related failure </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Error response </td><td>  -  </td></tr>
     </table>
     */
    public APIgetMcpToolRequest getMcpTool(String scope, String code) {
        return new APIgetMcpToolRequest(scope, code);
    }
    private okhttp3.Call listMcpToolsCall(final ApiCallback _callback) throws ApiException {
        return listMcpToolsCall( _callback, new ConfigurationOptions());
    }

    private okhttp3.Call listMcpToolsCall(final ApiCallback _callback, ConfigurationOptions opts) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/mcptools";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "oauth2" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback, opts);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listMcpToolsValidateBeforeCall(final ApiCallback _callback, ConfigurationOptions opts) throws ApiException {
        return listMcpToolsCall(_callback, opts);

    }


    private ApiResponse<List<McpToolResponse>> listMcpToolsWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = listMcpToolsValidateBeforeCall(null, new ConfigurationOptions());
        Type localVarReturnType = new TypeToken<List<McpToolResponse>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private ApiResponse<List<McpToolResponse>> listMcpToolsWithHttpInfo(ConfigurationOptions opts) throws ApiException {
        okhttp3.Call localVarCall = listMcpToolsValidateBeforeCall(null, opts);
        Type localVarReturnType = new TypeToken<List<McpToolResponse>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call listMcpToolsAsync(final ApiCallback<List<McpToolResponse>> _callback) throws ApiException {

        okhttp3.Call localVarCall = listMcpToolsValidateBeforeCall(_callback, new ConfigurationOptions());
        Type localVarReturnType = new TypeToken<List<McpToolResponse>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    private okhttp3.Call listMcpToolsAsync(final ApiCallback<List<McpToolResponse>> _callback, ConfigurationOptions opts) throws ApiException {

        okhttp3.Call localVarCall = listMcpToolsValidateBeforeCall(_callback, opts);
        Type localVarReturnType = new TypeToken<List<McpToolResponse>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class APIlistMcpToolsRequest {

        private APIlistMcpToolsRequest() {
        }

        /**
         * Build call for listMcpTools
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> List MCP Tools </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Error response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return listMcpToolsCall(_callback);
        }

        /**
         * Execute listMcpTools request
         * @return List&lt;McpToolResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> List MCP Tools </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Error response </td><td>  -  </td></tr>
         </table>
         */
        public List<McpToolResponse> execute() throws ApiException {
            ApiResponse<List<McpToolResponse>> localVarResp = listMcpToolsWithHttpInfo();
            return localVarResp.getData();
        }

        /**
         * Execute listMcpTools request. Use any specified configuration options to override any other configuration for this request only.
         * @return List&lt;McpToolResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> List MCP Tools </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Error response </td><td>  -  </td></tr>
         </table>
         */
        public List<McpToolResponse> execute(ConfigurationOptions opts) throws ApiException {
            ApiResponse<List<McpToolResponse>> localVarResp = listMcpToolsWithHttpInfo(opts);
            return localVarResp.getData();
        }

        /**
         * Execute listMcpTools request with HTTP info returned
         * @return ApiResponse&lt;List&lt;McpToolResponse&gt;&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> List MCP Tools </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Error response </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<List<McpToolResponse>> executeWithHttpInfo() throws ApiException {
            return listMcpToolsWithHttpInfo();
        }

        /**
         * Execute listMcpTools request with HTTP info returned. Use any specified configuration options to override any other configuration for this request only.
         * @return ApiResponse&lt;List&lt;McpToolResponse&gt;&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> List MCP Tools </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Error response </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<List<McpToolResponse>> executeWithHttpInfo(ConfigurationOptions opts) throws ApiException {
            return listMcpToolsWithHttpInfo(opts);
        }

        /**
         * Execute listMcpTools request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> List MCP Tools </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Error response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<List<McpToolResponse>> _callback) throws ApiException {
            return listMcpToolsAsync(_callback);
        }

        /**
         * Execute listMcpTools request (asynchronously). Use any specified configuration options to override any other configuration for this request only.
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> List MCP Tools </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Error response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<List<McpToolResponse>> _callback, ConfigurationOptions opts) throws ApiException {
            return listMcpToolsAsync(_callback, opts);
        }
    }

    /**
     * [EARLY ACCESS] ListMcpTools: List all MCP Tools
     * Lists all current MCP tools for the domain
     * @return APIlistMcpToolsRequest
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List MCP Tools </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Error response </td><td>  -  </td></tr>
     </table>
     */
    public APIlistMcpToolsRequest listMcpTools() {
        return new APIlistMcpToolsRequest();
    }
    private okhttp3.Call updateMcpToolCall(String scope, String code, UpsertMcpToolRequest upsertMcpToolRequest, final ApiCallback _callback) throws ApiException {
        return updateMcpToolCall(scope, code, upsertMcpToolRequest,  _callback, new ConfigurationOptions());
    }

    private okhttp3.Call updateMcpToolCall(String scope, String code, UpsertMcpToolRequest upsertMcpToolRequest, final ApiCallback _callback, ConfigurationOptions opts) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = upsertMcpToolRequest;

        // create path and map variables
        String localVarPath = "/api/mcptools/{scope}/{code}"
            .replace("{" + "scope" + "}", localVarApiClient.escapeString(scope.toString()))
            .replace("{" + "code" + "}", localVarApiClient.escapeString(code.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json-patch+json",
            "application/json",
            "text/json",
            "application/*+json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "oauth2" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback, opts);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateMcpToolValidateBeforeCall(String scope, String code, UpsertMcpToolRequest upsertMcpToolRequest, final ApiCallback _callback, ConfigurationOptions opts) throws ApiException {
        // verify the required parameter 'scope' is set
        if (scope == null) {
            throw new ApiException("Missing the required parameter 'scope' when calling updateMcpTool(Async)");
        }

        // verify the required parameter 'code' is set
        if (code == null) {
            throw new ApiException("Missing the required parameter 'code' when calling updateMcpTool(Async)");
        }

        // verify the required parameter 'upsertMcpToolRequest' is set
        if (upsertMcpToolRequest == null) {
            throw new ApiException("Missing the required parameter 'upsertMcpToolRequest' when calling updateMcpTool(Async)");
        }

        return updateMcpToolCall(scope, code, upsertMcpToolRequest, _callback, opts);

    }


    private ApiResponse<McpToolResponse> updateMcpToolWithHttpInfo(String scope, String code, UpsertMcpToolRequest upsertMcpToolRequest) throws ApiException {
        okhttp3.Call localVarCall = updateMcpToolValidateBeforeCall(scope, code, upsertMcpToolRequest, null, new ConfigurationOptions());
        Type localVarReturnType = new TypeToken<McpToolResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private ApiResponse<McpToolResponse> updateMcpToolWithHttpInfo(String scope, String code, UpsertMcpToolRequest upsertMcpToolRequest, ConfigurationOptions opts) throws ApiException {
        okhttp3.Call localVarCall = updateMcpToolValidateBeforeCall(scope, code, upsertMcpToolRequest, null, opts);
        Type localVarReturnType = new TypeToken<McpToolResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call updateMcpToolAsync(String scope, String code, UpsertMcpToolRequest upsertMcpToolRequest, final ApiCallback<McpToolResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateMcpToolValidateBeforeCall(scope, code, upsertMcpToolRequest, _callback, new ConfigurationOptions());
        Type localVarReturnType = new TypeToken<McpToolResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    private okhttp3.Call updateMcpToolAsync(String scope, String code, UpsertMcpToolRequest upsertMcpToolRequest, final ApiCallback<McpToolResponse> _callback, ConfigurationOptions opts) throws ApiException {

        okhttp3.Call localVarCall = updateMcpToolValidateBeforeCall(scope, code, upsertMcpToolRequest, _callback, opts);
        Type localVarReturnType = new TypeToken<McpToolResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class APIupdateMcpToolRequest {
        private final String scope;
        private final String code;
        private final UpsertMcpToolRequest upsertMcpToolRequest;

        private APIupdateMcpToolRequest(String scope, String code, UpsertMcpToolRequest upsertMcpToolRequest) {
            this.scope = scope;
            this.code = code;
            this.upsertMcpToolRequest = upsertMcpToolRequest;
        }

        /**
         * Build call for updateMcpTool
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Update MCP Tool </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> The details of the input related failure </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Error response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return updateMcpToolCall(scope, code, upsertMcpToolRequest, _callback);
        }

        /**
         * Execute updateMcpTool request
         * @return McpToolResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Update MCP Tool </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> The details of the input related failure </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Error response </td><td>  -  </td></tr>
         </table>
         */
        public McpToolResponse execute() throws ApiException {
            ApiResponse<McpToolResponse> localVarResp = updateMcpToolWithHttpInfo(scope, code, upsertMcpToolRequest);
            return localVarResp.getData();
        }

        /**
         * Execute updateMcpTool request. Use any specified configuration options to override any other configuration for this request only.
         * @return McpToolResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Update MCP Tool </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> The details of the input related failure </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Error response </td><td>  -  </td></tr>
         </table>
         */
        public McpToolResponse execute(ConfigurationOptions opts) throws ApiException {
            ApiResponse<McpToolResponse> localVarResp = updateMcpToolWithHttpInfo(scope, code, upsertMcpToolRequest, opts);
            return localVarResp.getData();
        }

        /**
         * Execute updateMcpTool request with HTTP info returned
         * @return ApiResponse&lt;McpToolResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Update MCP Tool </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> The details of the input related failure </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Error response </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<McpToolResponse> executeWithHttpInfo() throws ApiException {
            return updateMcpToolWithHttpInfo(scope, code, upsertMcpToolRequest);
        }

        /**
         * Execute updateMcpTool request with HTTP info returned. Use any specified configuration options to override any other configuration for this request only.
         * @return ApiResponse&lt;McpToolResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Update MCP Tool </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> The details of the input related failure </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Error response </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<McpToolResponse> executeWithHttpInfo(ConfigurationOptions opts) throws ApiException {
            return updateMcpToolWithHttpInfo(scope, code, upsertMcpToolRequest, opts);
        }

        /**
         * Execute updateMcpTool request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Update MCP Tool </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> The details of the input related failure </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Error response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<McpToolResponse> _callback) throws ApiException {
            return updateMcpToolAsync(scope, code, upsertMcpToolRequest, _callback);
        }

        /**
         * Execute updateMcpTool request (asynchronously). Use any specified configuration options to override any other configuration for this request only.
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Update MCP Tool </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> The details of the input related failure </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Error response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<McpToolResponse> _callback, ConfigurationOptions opts) throws ApiException {
            return updateMcpToolAsync(scope, code, upsertMcpToolRequest, _callback, opts);
        }
    }

    /**
     * [EARLY ACCESS] UpdateMcpTool: Update an MCP Tool
     * Updates an existing MCP tool, creating a new version
     * @param scope The scope of the MCP tool (required)
     * @param code The code of the MCP tool (required)
     * @param upsertMcpToolRequest The updated MCP tool definition (required)
     * @return APIupdateMcpToolRequest
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Update MCP Tool </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The details of the input related failure </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Error response </td><td>  -  </td></tr>
     </table>
     */
    public APIupdateMcpToolRequest updateMcpTool(String scope, String code, UpsertMcpToolRequest upsertMcpToolRequest) {
        return new APIupdateMcpToolRequest(scope, code, upsertMcpToolRequest);
    }
}
