/*
 * FINBOURNE Identity Service API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.identity.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.identity.JSON;

/**
 * Response containing the current cell parent status.
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class CellParentStatusResponse {
  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_ADMIN_DOMAIN_NAME = "adminDomainName";
  @SerializedName(SERIALIZED_NAME_ADMIN_DOMAIN_NAME)
  private String adminDomainName;

  public static final String SERIALIZED_NAME_PRIMARY_DOMAIN_NAME = "primaryDomainName";
  @SerializedName(SERIALIZED_NAME_PRIMARY_DOMAIN_NAME)
  private String primaryDomainName;

  public static final String SERIALIZED_NAME_REGISTRATION_STEP = "registrationStep";
  @SerializedName(SERIALIZED_NAME_REGISTRATION_STEP)
  private String registrationStep;

  public static final String SERIALIZED_NAME_REGISTRATION_ERROR = "registrationError";
  @SerializedName(SERIALIZED_NAME_REGISTRATION_ERROR)
  private String registrationError;

  public CellParentStatusResponse() {
  }

  public CellParentStatusResponse status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * The current attachment status of the cell.
   * @return status
  **/
  @jakarta.annotation.Nullable
  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    this.status = status;
  }


  public CellParentStatusResponse adminDomainName(String adminDomainName) {
    
    this.adminDomainName = adminDomainName;
    return this;
  }

   /**
   * The name of the admin domain in the parent cell, if any.
   * @return adminDomainName
  **/
  @jakarta.annotation.Nullable
  public String getAdminDomainName() {
    return adminDomainName;
  }


  public void setAdminDomainName(String adminDomainName) {
    this.adminDomainName = adminDomainName;
  }


  public CellParentStatusResponse primaryDomainName(String primaryDomainName) {
    
    this.primaryDomainName = primaryDomainName;
    return this;
  }

   /**
   * The domain designated as the primary domain for this cell, if any.
   * @return primaryDomainName
  **/
  @jakarta.annotation.Nullable
  public String getPrimaryDomainName() {
    return primaryDomainName;
  }


  public void setPrimaryDomainName(String primaryDomainName) {
    this.primaryDomainName = primaryDomainName;
  }


  public CellParentStatusResponse registrationStep(String registrationStep) {
    
    this.registrationStep = registrationStep;
    return this;
  }

   /**
   * The most recently reached registration checkpoint, or null if no registration has started. One of &#x60;UserEnsured&#x60;, &#x60;PATGenerated&#x60;, &#x60;PATPushed&#x60;.
   * @return registrationStep
  **/
  @jakarta.annotation.Nullable
  public String getRegistrationStep() {
    return registrationStep;
  }


  public void setRegistrationStep(String registrationStep) {
    this.registrationStep = registrationStep;
  }


  public CellParentStatusResponse registrationError(String registrationError) {
    
    this.registrationError = registrationError;
    return this;
  }

   /**
   * Operator-readable message describing the most recent registration failure, or null on success.
   * @return registrationError
  **/
  @jakarta.annotation.Nullable
  public String getRegistrationError() {
    return registrationError;
  }


  public void setRegistrationError(String registrationError) {
    this.registrationError = registrationError;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CellParentStatusResponse cellParentStatusResponse = (CellParentStatusResponse) o;
    return Objects.equals(this.status, cellParentStatusResponse.status) &&
        Objects.equals(this.adminDomainName, cellParentStatusResponse.adminDomainName) &&
        Objects.equals(this.primaryDomainName, cellParentStatusResponse.primaryDomainName) &&
        Objects.equals(this.registrationStep, cellParentStatusResponse.registrationStep) &&
        Objects.equals(this.registrationError, cellParentStatusResponse.registrationError);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, adminDomainName, primaryDomainName, registrationStep, registrationError);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CellParentStatusResponse {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    adminDomainName: ").append(toIndentedString(adminDomainName)).append("\n");
    sb.append("    primaryDomainName: ").append(toIndentedString(primaryDomainName)).append("\n");
    sb.append("    registrationStep: ").append(toIndentedString(registrationStep)).append("\n");
    sb.append("    registrationError: ").append(toIndentedString(registrationError)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("status");
    openapiFields.add("adminDomainName");
    openapiFields.add("primaryDomainName");
    openapiFields.add("registrationStep");
    openapiFields.add("registrationError");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to CellParentStatusResponse
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CellParentStatusResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CellParentStatusResponse is not found in the empty JSON string", CellParentStatusResponse.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      if ((jsonObj.get("adminDomainName") != null && !jsonObj.get("adminDomainName").isJsonNull()) && !jsonObj.get("adminDomainName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `adminDomainName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("adminDomainName").toString()));
      }
      if ((jsonObj.get("primaryDomainName") != null && !jsonObj.get("primaryDomainName").isJsonNull()) && !jsonObj.get("primaryDomainName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `primaryDomainName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("primaryDomainName").toString()));
      }
      if ((jsonObj.get("registrationStep") != null && !jsonObj.get("registrationStep").isJsonNull()) && !jsonObj.get("registrationStep").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `registrationStep` to be a primitive type in the JSON string but got `%s`", jsonObj.get("registrationStep").toString()));
      }
      if ((jsonObj.get("registrationError") != null && !jsonObj.get("registrationError").isJsonNull()) && !jsonObj.get("registrationError").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `registrationError` to be a primitive type in the JSON string but got `%s`", jsonObj.get("registrationError").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CellParentStatusResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CellParentStatusResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CellParentStatusResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CellParentStatusResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<CellParentStatusResponse>() {
           @Override
           public void write(JsonWriter out, CellParentStatusResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CellParentStatusResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CellParentStatusResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CellParentStatusResponse
  * @throws IOException if the JSON string is invalid with respect to CellParentStatusResponse
  */
  public static CellParentStatusResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CellParentStatusResponse.class);
  }

 /**
  * Convert an instance of CellParentStatusResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
