/*
 * FINBOURNE Identity Service API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.identity.model;

import java.util.Objects;
import com.finbourne.identity.model.PasswordPolicyResponseAge;
import com.finbourne.identity.model.PasswordPolicyResponseComplexity;
import com.finbourne.identity.model.PasswordPolicyResponseLockout;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.identity.JSON;

/**
 * Password policy conditions for a password policy
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class PasswordPolicyResponseConditions {
  public static final String SERIALIZED_NAME_COMPLEXITY = "complexity";
  @SerializedName(SERIALIZED_NAME_COMPLEXITY)
  private PasswordPolicyResponseComplexity complexity;

  public static final String SERIALIZED_NAME_AGE = "age";
  @SerializedName(SERIALIZED_NAME_AGE)
  private PasswordPolicyResponseAge age;

  public static final String SERIALIZED_NAME_LOCKOUT = "lockout";
  @SerializedName(SERIALIZED_NAME_LOCKOUT)
  private PasswordPolicyResponseLockout lockout;

  public PasswordPolicyResponseConditions() {
  }

  public PasswordPolicyResponseConditions complexity(PasswordPolicyResponseComplexity complexity) {
    
    this.complexity = complexity;
    return this;
  }

   /**
   * Get complexity
   * @return complexity
  **/
  @jakarta.annotation.Nonnull
  public PasswordPolicyResponseComplexity getComplexity() {
    return complexity;
  }


  public void setComplexity(PasswordPolicyResponseComplexity complexity) {
    this.complexity = complexity;
  }


  public PasswordPolicyResponseConditions age(PasswordPolicyResponseAge age) {
    
    this.age = age;
    return this;
  }

   /**
   * Get age
   * @return age
  **/
  @jakarta.annotation.Nonnull
  public PasswordPolicyResponseAge getAge() {
    return age;
  }


  public void setAge(PasswordPolicyResponseAge age) {
    this.age = age;
  }


  public PasswordPolicyResponseConditions lockout(PasswordPolicyResponseLockout lockout) {
    
    this.lockout = lockout;
    return this;
  }

   /**
   * Get lockout
   * @return lockout
  **/
  @jakarta.annotation.Nonnull
  public PasswordPolicyResponseLockout getLockout() {
    return lockout;
  }


  public void setLockout(PasswordPolicyResponseLockout lockout) {
    this.lockout = lockout;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PasswordPolicyResponseConditions passwordPolicyResponseConditions = (PasswordPolicyResponseConditions) o;
    return Objects.equals(this.complexity, passwordPolicyResponseConditions.complexity) &&
        Objects.equals(this.age, passwordPolicyResponseConditions.age) &&
        Objects.equals(this.lockout, passwordPolicyResponseConditions.lockout);
  }

  @Override
  public int hashCode() {
    return Objects.hash(complexity, age, lockout);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PasswordPolicyResponseConditions {\n");
    sb.append("    complexity: ").append(toIndentedString(complexity)).append("\n");
    sb.append("    age: ").append(toIndentedString(age)).append("\n");
    sb.append("    lockout: ").append(toIndentedString(lockout)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("complexity");
    openapiFields.add("age");
    openapiFields.add("lockout");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("complexity");
    openapiRequiredFields.add("age");
    openapiRequiredFields.add("lockout");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to PasswordPolicyResponseConditions
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PasswordPolicyResponseConditions.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PasswordPolicyResponseConditions is not found in the empty JSON string", PasswordPolicyResponseConditions.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PasswordPolicyResponseConditions.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `complexity`
      PasswordPolicyResponseComplexity.validateJsonElement(jsonObj.get("complexity"));
      // validate the required field `age`
      PasswordPolicyResponseAge.validateJsonElement(jsonObj.get("age"));
      // validate the required field `lockout`
      PasswordPolicyResponseLockout.validateJsonElement(jsonObj.get("lockout"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PasswordPolicyResponseConditions.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PasswordPolicyResponseConditions' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PasswordPolicyResponseConditions> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PasswordPolicyResponseConditions.class));

       return (TypeAdapter<T>) new TypeAdapter<PasswordPolicyResponseConditions>() {
           @Override
           public void write(JsonWriter out, PasswordPolicyResponseConditions value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PasswordPolicyResponseConditions read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PasswordPolicyResponseConditions given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PasswordPolicyResponseConditions
  * @throws IOException if the JSON string is invalid with respect to PasswordPolicyResponseConditions
  */
  public static PasswordPolicyResponseConditions fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PasswordPolicyResponseConditions.class);
  }

 /**
  * Convert an instance of PasswordPolicyResponseConditions to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
