/*
 * FINBOURNE Identity Service API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.identity.model;

import java.util.Objects;
import com.finbourne.identity.model.SupportRole;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.identity.JSON;

/**
 * SupportRolesResponse
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SupportRolesResponse {
  public static final String SERIALIZED_NAME_SUPPORT_ROLES = "supportRoles";
  @SerializedName(SERIALIZED_NAME_SUPPORT_ROLES)
  private List<SupportRole> supportRoles;

  public SupportRolesResponse() {
  }

  public SupportRolesResponse supportRoles(List<SupportRole> supportRoles) {
    
    this.supportRoles = supportRoles;
    return this;
  }

  public SupportRolesResponse addSupportRolesItem(SupportRole supportRolesItem) {
    if (this.supportRoles == null) {
      this.supportRoles = new ArrayList<>();
    }
    this.supportRoles.add(supportRolesItem);
    return this;
  }

   /**
   * Get supportRoles
   * @return supportRoles
  **/
  @jakarta.annotation.Nullable
  public List<SupportRole> getSupportRoles() {
    return supportRoles;
  }


  public void setSupportRoles(List<SupportRole> supportRoles) {
    this.supportRoles = supportRoles;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SupportRolesResponse supportRolesResponse = (SupportRolesResponse) o;
    return Objects.equals(this.supportRoles, supportRolesResponse.supportRoles);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(supportRoles);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SupportRolesResponse {\n");
    sb.append("    supportRoles: ").append(toIndentedString(supportRoles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("supportRoles");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to SupportRolesResponse
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SupportRolesResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SupportRolesResponse is not found in the empty JSON string", SupportRolesResponse.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("supportRoles") != null && !jsonObj.get("supportRoles").isJsonNull()) {
        JsonArray jsonArraysupportRoles = jsonObj.getAsJsonArray("supportRoles");
        if (jsonArraysupportRoles != null) {
          // ensure the json data is an array
          if (!jsonObj.get("supportRoles").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `supportRoles` to be an array in the JSON string but got `%s`", jsonObj.get("supportRoles").toString()));
          }

          // validate the optional field `supportRoles` (array)
          for (int i = 0; i < jsonArraysupportRoles.size(); i++) {
            SupportRole.validateJsonElement(jsonArraysupportRoles.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SupportRolesResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SupportRolesResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SupportRolesResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SupportRolesResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<SupportRolesResponse>() {
           @Override
           public void write(JsonWriter out, SupportRolesResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SupportRolesResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SupportRolesResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SupportRolesResponse
  * @throws IOException if the JSON string is invalid with respect to SupportRolesResponse
  */
  public static SupportRolesResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SupportRolesResponse.class);
  }

 /**
  * Convert an instance of SupportRolesResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
