/*
 * FINBOURNE Identity Service API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.identity.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.identity.JSON;

/**
 * Session timing settings.
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class UpdateSessionPolicyRequest {
  public static final String SERIALIZED_NAME_MAX_SESSION_IDLE_MINUTES = "maxSessionIdleMinutes";
  @SerializedName(SERIALIZED_NAME_MAX_SESSION_IDLE_MINUTES)
  private Long maxSessionIdleMinutes;

  public static final String SERIALIZED_NAME_MAX_SESSION_LIFETIME_MINUTES = "maxSessionLifetimeMinutes";
  @SerializedName(SERIALIZED_NAME_MAX_SESSION_LIFETIME_MINUTES)
  private Long maxSessionLifetimeMinutes;

  public UpdateSessionPolicyRequest() {
  }

  public UpdateSessionPolicyRequest maxSessionIdleMinutes(Long maxSessionIdleMinutes) {
    
    this.maxSessionIdleMinutes = maxSessionIdleMinutes;
    return this;
  }

   /**
   * Maximum minutes a user&#39;s session can be idle before re-authentication is required. Must be between 5 minutes and 12 hours (720 minutes).
   * minimum: 5
   * maximum: 720
   * @return maxSessionIdleMinutes
  **/
  @jakarta.annotation.Nonnull
  public Long getMaxSessionIdleMinutes() {
    return maxSessionIdleMinutes;
  }


  public void setMaxSessionIdleMinutes(Long maxSessionIdleMinutes) {
    this.maxSessionIdleMinutes = maxSessionIdleMinutes;
  }


  public UpdateSessionPolicyRequest maxSessionLifetimeMinutes(Long maxSessionLifetimeMinutes) {
    
    this.maxSessionLifetimeMinutes = maxSessionLifetimeMinutes;
    return this;
  }

   /**
   * Maximum minutes a user&#39;s session can live in total. Omit to disable session expiry; otherwise must be between 5 minutes and 24 hours (1440 minutes).
   * minimum: 5
   * maximum: 1440
   * @return maxSessionLifetimeMinutes
  **/
  @jakarta.annotation.Nullable
  public Long getMaxSessionLifetimeMinutes() {
    return maxSessionLifetimeMinutes;
  }


  public void setMaxSessionLifetimeMinutes(Long maxSessionLifetimeMinutes) {
    this.maxSessionLifetimeMinutes = maxSessionLifetimeMinutes;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateSessionPolicyRequest updateSessionPolicyRequest = (UpdateSessionPolicyRequest) o;
    return Objects.equals(this.maxSessionIdleMinutes, updateSessionPolicyRequest.maxSessionIdleMinutes) &&
        Objects.equals(this.maxSessionLifetimeMinutes, updateSessionPolicyRequest.maxSessionLifetimeMinutes);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(maxSessionIdleMinutes, maxSessionLifetimeMinutes);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateSessionPolicyRequest {\n");
    sb.append("    maxSessionIdleMinutes: ").append(toIndentedString(maxSessionIdleMinutes)).append("\n");
    sb.append("    maxSessionLifetimeMinutes: ").append(toIndentedString(maxSessionLifetimeMinutes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("maxSessionIdleMinutes");
    openapiFields.add("maxSessionLifetimeMinutes");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("maxSessionIdleMinutes");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to UpdateSessionPolicyRequest
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UpdateSessionPolicyRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UpdateSessionPolicyRequest is not found in the empty JSON string", UpdateSessionPolicyRequest.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : UpdateSessionPolicyRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UpdateSessionPolicyRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UpdateSessionPolicyRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UpdateSessionPolicyRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UpdateSessionPolicyRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<UpdateSessionPolicyRequest>() {
           @Override
           public void write(JsonWriter out, UpdateSessionPolicyRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UpdateSessionPolicyRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of UpdateSessionPolicyRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of UpdateSessionPolicyRequest
  * @throws IOException if the JSON string is invalid with respect to UpdateSessionPolicyRequest
  */
  public static UpdateSessionPolicyRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UpdateSessionPolicyRequest.class);
  }

 /**
  * Convert an instance of UpdateSessionPolicyRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
