/*
 * FINBOURNE Identity Service API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.identity.model;

import java.util.Objects;
import com.finbourne.identity.model.UserSchemaProperty;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.identity.JSON;

/**
 * UserSchemaResponse
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class UserSchemaResponse {
  public static final String SERIALIZED_NAME_ALTERNATIVE_USER_IDS = "alternativeUserIds";
  @SerializedName(SERIALIZED_NAME_ALTERNATIVE_USER_IDS)
  private List<UserSchemaProperty> alternativeUserIds;

  public UserSchemaResponse() {
  }

  public UserSchemaResponse alternativeUserIds(List<UserSchemaProperty> alternativeUserIds) {
    
    this.alternativeUserIds = alternativeUserIds;
    return this;
  }

  public UserSchemaResponse addAlternativeUserIdsItem(UserSchemaProperty alternativeUserIdsItem) {
    if (this.alternativeUserIds == null) {
      this.alternativeUserIds = new ArrayList<>();
    }
    this.alternativeUserIds.add(alternativeUserIdsItem);
    return this;
  }

   /**
   * Get alternativeUserIds
   * @return alternativeUserIds
  **/
  @jakarta.annotation.Nullable
  public List<UserSchemaProperty> getAlternativeUserIds() {
    return alternativeUserIds;
  }


  public void setAlternativeUserIds(List<UserSchemaProperty> alternativeUserIds) {
    this.alternativeUserIds = alternativeUserIds;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserSchemaResponse userSchemaResponse = (UserSchemaResponse) o;
    return Objects.equals(this.alternativeUserIds, userSchemaResponse.alternativeUserIds);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(alternativeUserIds);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserSchemaResponse {\n");
    sb.append("    alternativeUserIds: ").append(toIndentedString(alternativeUserIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("alternativeUserIds");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to UserSchemaResponse
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UserSchemaResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UserSchemaResponse is not found in the empty JSON string", UserSchemaResponse.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("alternativeUserIds") != null && !jsonObj.get("alternativeUserIds").isJsonNull()) {
        JsonArray jsonArrayalternativeUserIds = jsonObj.getAsJsonArray("alternativeUserIds");
        if (jsonArrayalternativeUserIds != null) {
          // ensure the json data is an array
          if (!jsonObj.get("alternativeUserIds").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `alternativeUserIds` to be an array in the JSON string but got `%s`", jsonObj.get("alternativeUserIds").toString()));
          }

          // validate the optional field `alternativeUserIds` (array)
          for (int i = 0; i < jsonArrayalternativeUserIds.size(); i++) {
            UserSchemaProperty.validateJsonElement(jsonArrayalternativeUserIds.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UserSchemaResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UserSchemaResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UserSchemaResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UserSchemaResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<UserSchemaResponse>() {
           @Override
           public void write(JsonWriter out, UserSchemaResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UserSchemaResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of UserSchemaResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of UserSchemaResponse
  * @throws IOException if the JSON string is invalid with respect to UserSchemaResponse
  */
  public static UserSchemaResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UserSchemaResponse.class);
  }

 /**
  * Convert an instance of UserSchemaResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
